apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: mc-keycloak-rt
  namespace: gloo-mesh-gateways
spec:
  hosts:
  #- keycloak.keycloak.svc.cluster.local
  - mc-keycloak.example.com
  virtualGateways:
  - name: istio-ingressgateway
    namespace: gloo-mesh-gateways
  http:
  - name: mc-keycloak
    labels:
      cors-policy: microcks
    matchers:
    - uri:
        prefix: /
    forwardTo:
      destinations:
        - ref:
            name: microcks-keycloak
            namespace: microcks
            cluster: gg-demo-single
          port:
            number: 8080
  # tls:
  # - forwardTo:
  #     destinations:
  #     - port:
  #         number: 8080
  #       ref:
  #         cluster: gg-demo-single
  #         name: microcks-keycloak
  #         namespace: microcks
  #   matchers:
  #   - port: 443
  #     sniHosts:
  #     - mc-keycloak.example.com
