gloo:
  settings:
    disableKubernetesDestinations: true
  discovery:
    enabled: true
  gateway:
    # Configure Validating Admission Webhook to reject resources (normally invalid resources are only logged).
    validation:
      enabled: true
      # Reject invalid resources (resources that would result in an error state)
      alwaysAcceptResources: false
      # Reject resources that would result in a warning
      allowWarnings: false
      # Disable validation webhook when deleting the following resources.
      # webhook:
      #   skipDeleteValidationResources:
      #   - virtualservices
      #   - routetables
      #   - upstreams
      #   - secrets
      #   - ratelimitconfigs
  gatewayProxies:
    gatewayProxy:
      gatewaySettings:
        accessLoggingService:
          accessLog:
          - fileSink:
              path: /dev/stdout
              stringFormat: ""
